language: ruby
sudo: false
rvm:
  - 2.7
  - 2.6
  - 2.5
gemfile:
  - gemfiles/Gemfile-rails.5.1.x
  - gemfiles/Gemfile-rails.5.2.x
  - gemfiles/Gemfile-rails.6.0.x
before_script:
  - "cd test/dummy; rake db:migrate; rake db:test:prepare; cd ../.."
notifications:
  email: false
